# 1. Python program to find max number

In [ ]:

N=int(input("Enter the number of numbers you want to enter:"))
L=[]
max=0
for i in range(N):
  n=int(input("Enter the {}th number:".format(i+1)))
  L.append(n)
  if(n>max):
    max=n

print("Given list:",L)
print("largest no.:",max)

Enter the number of numbers you want to enter:3
Enter the 1th number:5
Enter the 2th number:2
Enter the 3th number:56
Given list: [5, 2, 56]
largest no.: 56

# 2. Write a program that will convert celsius value to fahrenheit

In [ ]:
c=float(input("enter the temp in celsius:"))
f=(c*9/5)+32
print("temp in fahrenheit:",f)

enter the temp in celsius:38.2
temp in fahrenheit: 100.76

# 3. User will input (2numbers).Write a program to swap the numbers

In [ ]:
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))

print("Before Swapping numbers are:",a,b)

# tem=a
# a=b
# b=tem
# print("After Swapping numbers are:",a,b)


a=a+b
b=a-b
a=a-b
print("After Swapping numbers are:",a,b)

Enter first number:5
Enter second number:6
Before Swapping numbers are: 5 6
After Swapping numbers are: 6 5

# 4. Write a program that will give you the sum of 3 digits

In [ ]:
n=int(input("Enter the 3 digit number:"))

sum=0

while(n>0):
  x=n%10
  sum+=x
  n=n//10

print("Sum of digits:",sum)

Enter the 3 digit number:123
Sum of digits: 6

# 5. Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

In [ ]:
n=int(input("Enter the 4 digit number:"))
N=n
rev_n=0

while(n>0):
  a=n%10
  n=n//10
  rev_n=rev_n*10+a

print("Reverse of the number:",rev_n)

if(N == rev_n):
  print("Reverse is True")
else:
  print("Reverse is False")

Enter the 4 digit number:251
Reverse of the number: 152
Reverse is False

# 6. Write a program that will tell whether the number entered by the user is odd or even.

In [ ]:
n=int(input("Enter a number:"))

if(n%2==0):
  print("Even")
else:
  print("Odd")

Enter a number:585
Odd

# 7. Write a program that will tell whether the given year is a leap year or not.

In [ ]:
yr=int(input("Enter the year:"))

end_two_digits=yr%100
if(end_two_digits==0):
  if(yr%400==0):
    print("Leap Year")

  else:
    print("Not a Leap Year")

else:
  if(yr%4==0):
    print("Leap Year")
  else:
    print("Not a Leap Year")

Enter the year:2024
Leap Year

# 8. Write a program to find the euclidean distance between two coordinates.

In [ ]:
import math

x1=int(input("Enter x1:"))
y1=int(input("Enter y1:"))
x2=int(input("Enter x2:"))
y2=int(input("Enter y2:"))

euc_dist=math.sqrt((x2-x1)**2+(y2-y1)**2)

print("Euclidean Distance between both points:",euc_dist)

Enter x1:1
Enter y1:2
Enter x2:5
Enter y2:5
Euclidean Distance between both points: 5.0

# 9. Write a program that take a user input of three angles and will find out whether it can form a triangle or not.

In [ ]:
sum=0
for i in range(3):
  angle=int(input("Enter the {}th angle:".format(i+1)))
  sum+=angle

if(sum==180):
  print("Triangle can be formed")
else:
  print("Triangle cannot be formed")

Enter the 1th angle:90
Enter the 2th angle:20
Enter the 3th angle:70
Triangle can be formed

# 10. Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit

In [ ]:
cp=int(input("Enter the cost price of the product:"))
sp=int(input("Enter the selling price of the product:"))

margin=sp-cp

if(margin>0):
  print("Profit of",margin)
else:
  margin*=-1
  print("Loss of ",margin)

Enter the cost price of the product:30
Enter the selling price of the product:100
Profit of 70

# 11. Write a program to find the simple interest when the value of principle,rate of interest and time period is given.

In [ ]:
P=float(input("Enter principal amount:"))
R=float(input("Enter ROI in % per annum:"))
T=float(input("Enter time in number of days"))

t=T/365
SI=(P*R*t)/100

print("Simple Interest:",SI)
print("Amount",P+SI)

Enter principal amount:1000
Enter ROI in % per annum:6.5
Enter time in number of days350
Simple Interest: 62.32876712328767
Amount 1062.3287671232877

# 12. Write a program to find the volume of the cylinder. Also find the cost when filled with milk ,when the cost of 1litre milk is 40Rs.

In [ ]:
import math

r=float(input("Enter the radius of the cylinder in centi_meter:"))
h=float(input("Enter the height of the cylinder in centi_meter:"))

vol=math.pi*r*r*h

print("Volume of the cylinder:",vol)

cost=(vol/1000)*40
print("Cost of the cylinder:",cost)

Enter the radius of the cylinder in meter:12
Enter the height of the cylinder in meter:10
Volume of the cylinder: 4523.893421169302
Cost of the cylinder: 180.95573684677208

# 13. Write  a program that will tell whether the given number is divisible by 3 & 6.

In [ ]:
n=int(input("Enter a number:"))
N=n
sum=0
while(n>0):
  sum=sum+n%10
  n=n//10

if (N%10)%2==0 and sum%3==0:
  print("Divisible by 3 and 6")
else:
  print("Not Divisible by 3 and 6")

Enter a number:72
Divisible by 3 and 6

#14. Calculate the angle between the hour hand and minute hand.

Note: There can be two angles between hands; we need to print a minimum of two. Also, we need to print the floor of the final result angle. For example, if the final angle is 10.61, we need to print 10.

In [ ]:
# minute hand 60 min m 360 degree --> 6 deg/min
# hour hand 12*60 min m 360 degree --> 0.5.deg/min

h=int(input("Enter the hours:"))
m=int(input("Enter the minutes:"))

angle_m=(m*6)%360
angle_h=((h*60+m)*0.5)%360

angle_between_hm1=abs(angle_h - angle_m)
angle_between_hm2=360 - angle_between_hm1

angle=min(angle_between_hm1,angle_between_hm2)

print(angle//1)

Enter the hours:9
Enter the minutes:60
60.0

# 15. Given two rectangles, find if the given two rectangles overlap or not. A rectangle is denoted by providing the x and y coordinates of two points: the left top corner and the right bottom corner of the rectangle. Two rectangles sharing a side are considered overlapping. (L1 and R1 are the extreme points of the first rectangle and L2 and R2 are the extreme points of the second rectangle).

Note: It may be assumed that the rectangles are parallel to the coordinate axis.

In [ ]:
L1=[]
R1=[]

L1x=int(input("Enter the x coordinate of leftmost point of first rectangle:"))
L1.append(L1x)
L1y=int(input("Enter the y coordinate of leftmost point of first rectangle:"))
L1.append(L1y)

R1x=int(input("Enter the x coordinate of rightmost point of first rectangle:"))
R1y=int(input("Enter the y coordinate of rightmost point of first rectangle:"))
R1.append(R1x)
R1.append(R1y)


L2=[]
R2=[]

print()
L2x=int(input("Enter the x coordinate of leftmost point of second rectangle:"))
L2.append(L2x)
L2y=int(input("Enter the y coordinate of leftmost point of second rectangle:"))
L2.append(L2y)

R2x=int(input("Enter the x coordinate of rightmost point of second rectangle:"))
R2y=int(input("Enter the y coordinate of rightmost point of second rectangle:"))
R2.append(R2x)
R2.append(R2y)

print()
print()
print("Leftmost point of first rectangle:",L1)
print("Rightmost point of first rectangle:",R1)
print()
print("Leftmost point of second rectangle:",L2)
print("Rightmost point of second rectangle:",R2)

# if rectangle has area 0, no overlap
if L1[0]==R1[0] or L1[1]==R1[1] or L2[0]==R2[0] or L2[1]==R2[1]:
  print("No overlap")

# If one rectangle is on left side of other
elif L1[0]>R2[0] or L2[0]>R1[0]:
  print("No overlap")

# If one rectangle is above other
elif L1[1]<R2[1] or L2[1]<R1[1]:
  print("No overlap")

else:
  print("Overlap")

Enter the x coordinate of leftmost point of first rectangle:0
Enter the y coordinate of leftmost point of first rectangle:10
Enter the x coordinate of rightmost point of first rectangle:10
Enter the y coordinate of rightmost point of first rectangle:0

Enter the x coordinate of leftmost point of second rectangle:5
Enter the y coordinate of leftmost point of second rectangle:5
Enter the x coordinate of rightmost point of second rectangle:15
Enter the y coordinate of rightmost point of second rectangle:0


Leftmost point of first rectangle: [0, 10]
Rightmost point of first rectangle: [10, 0]

Leftmost point of second rectangle: [5, 5]
Rightmost point of second rectangle: [15, 0]
Overlap

# 16.Write a program that will determine weather when the value of temperature and humidity is provided by the user.
TEMPERATURE(C)      HUMIDITY(%)      WEATHER

      >= 30                             >=90                Hot and Humid
      >= 30                             < 90                 Hot
      <30                                >= 90               Cool and Humid
      <30                                 <90                 Cool

In [ ]:
def Wheather():
  temp=float(input("Enter the temperature in celsius:"))
  hum=float(input("Enter the humidity :"))

  if(temp>=30):
    if(hum>=90):
      print("Wheather is Hot and Humid !!")

    else:
      print("Wheather is Hot !!")

  else:
    if(hum>=90):
      print("Wheather is Cool and Humid !!")

    else:
      print("Wheather is Cool !!")

In [ ]:
Wheather()

Enter the temperature in celsius:32
Enter the humidity :90
Wheather is Hot and Humid !!

# 17. Write a program that will take three digits from the user and add the square of each digit.

In [ ]:
res=0
for i in range(3):
  x=int(input("Enter the {}th digit:".format(i+1)))
  res+=x**2

print("Sum of the square of each digit is:",res)

Enter the 1th digit:2
Enter the 2th digit:3
Enter the 3th digit:5
Sum of the square of each digit is: 38

# 18. Write a program that will check whether the number is armstrong number or not.
* **Armstrong number is a number that is equal to the sum of cubes of its digits.**

In [ ]:
n=int(input("Enter a number:"))
N=n
sum=0

while(n>0):
  x=n%10
  sum+=x**3
  n=n//10

if(N==sum):
  print("Armstrong Number")
else:
  print("Not an Armstrong Number")

Enter a number:372
Not an Armstrong Number

# 19. Write a program that will take user input of (4 digits number) and check whether the number is narcissist number or not.

* **here rather than taking cube of each number we take the power to each digit equal to number of digits in given number**

In [ ]:
def narcissist():
  n=int(input("Enter a four digit number:"))
  N=n
  sum=0
  while(n>0):
    x=n%10
    sum+=x**len(str(N))
    n=n//10
  print("Sum is:",sum)
  if(N==sum):
    print("Narcissist number")
  else:
    print("Not a Narcissist number")

In [ ]:
narcissist()

Enter a four digit number:1235
Sum is: 723
Not a Narcissist number

In [ ]:
narcissist()

Enter a four digit number:153
Sum is: 153
Narcissist number

# 20. Write a program that will give you the in hand salary after deduction of HRA(10%),DA(5%),PF(3%), and tax(if salary is between 5-10 lakh–10%),(11-20lakh–20%),(20< _   – 30%)(0-1lakh print k).

In [ ]:
def in_hand_salary():
  salary=float(input("Enter the annual salary in rupee:"))

  salary_hra=salary*0.1
  salary_da=salary*0.05
  salary_pf=salary*0.03

  sal_taxable=salary-salary_hra-salary_da-salary_pf

  tax=0

  if(sal_taxable>=500000 and sal_taxable<=1000000):
    tax=sal_taxable*0.1
    print("Tax amount:",tax)

  elif(sal_taxable>=1100000 and sal_taxable<=2000000):
    tax=sal_taxable*0.2
    print("Tax amount:",tax)

  else:
    tax=sal_taxable*0.3
    print("Tax amount:",tax)

  in_hand_sal=(sal_taxable-tax)/12
  print("Net in hand salary per month:",in_hand_sal)

  if(in_hand_sal>=10000000):
    print(in_hand_sal/10000000,"cr")

In [ ]:
in_hand_salary()

Enter the annual salary in rupee:1000000
Tax amount: 82000.0
Net in hand salary per month: 61500.0

# 21. Write a menu driven program - 1.cm to ft  2.km to miles  3.usd to inr  4.exit

In [ ]:
print("Welcome to unit conversion tool !!\n")

while(True):
  print("\n\nMain Menu")
  print("option 1. cm to ft")
  print("option 2. km to miles")
  print("option 3. usd to inr")
  print("option 4. exit")
  choice=int(input("\n\nSelect any one of the option:"))

  if(choice==1):
    cm=float(input("\n\nEnter the length in cm:"))
    ft=cm/30.48
    print("Length in ft(cm to ft):",ft)


  elif(choice==2):
    km=float(input("\n\nEnter the length in km:"))
    miles=km/1.609
    print("Length in miles(km to miles):",miles)


  elif(choice==3):
    usd=float(input("\n\nEnter the amount in usd:"))
    inr=usd*83.49
    print("Amount in inr(usd to inr):",inr)


  elif(choice==4):
    print("\n\nExiting...")
    break

  else:
    print("\nYou have entered an invalid Input !! \nPlease Enter a valid choice")

Welcome to unit conversion tool !!



Main Menu
option 1. cm to ft
option 2. km to miles
option 3. usd to inr
option 4. exit


Select any one of the option:4


Exiting...

# 22. Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

 30 heads 100 legs ===> 10 chick 20 dogs

In [ ]:
heads = int(input("Enter the total number of heads: "))
legs = int(input("Enter the total number of legs: "))

# Calculate number of dogs and chickens
d = (legs - 2 * heads) / 2
c = heads - d

# Check if d and c are non-negative integers
if d >= 0 and c >= 0 and d == int(d) and c == int(c):
    print("Number of dogs:", int(d))
    print("Number of chickens:", int(c))
else:
    print("No valid solution exists for the given inputs.")

Enter the total number of heads: 30
Enter the total number of legs: 100
Number of dogs: 20
Number of chickens: 10

# 23. Write a program that will swap numbers

In [ ]:
def swap(a,b):
  print("Before swapping numbers are:",a,b)
  a=a+b
  b=a-b
  a=a-b
  print("After Swapping numbers are:",a,b)

In [ ]:
swap(5,6)

Before swapping numbers are: 5 6
After Swapping numbers are: 6 5

# 24. Write a program to find the sum of first n numbers, where n will be provided by the user. Eg if the user provides n=10 the output should be 55.

In [ ]:
def sum_n(n):
  sum=n*(n+1)/2
  print("Sum of first",n,"numbers is:",sum)

In [ ]:
sum_n(10)

Sum of first 10 numbers is: 55.0

# 25. Write a program that can multiply 2 numbers provided by the user without using the * operator

In [ ]:
a=int(input("Enter first number:"))
b=int(input("Enter second number: "))

res=0
for i in range(b):
  res=a+res

print("Product of two numbers:",res)

Enter first number:6
Enter second number: 9
Product of two numbers: 54

# 26. Write a program that can find the factorial of a given number provided by the user.

In [ ]:
n=int(input("Enter a number for which you want to  find factorial:"))
fact=1

for i in range(1,n+1):
  fact*=i

print("Factorial of",n,"is:",fact)

Enter a number for which you want to  find factorial:5
Factorial of 5 is: 120

# 27. Write a program to print the first 25 odd numbers

In [ ]:
n=0
count=0

print("First 25 odd numbers are:")
while(count<25):
  if(n%2!=0):
    print(n,end="  ")
    n+=1
    count+=1
  else:
    n+=1

First 25 odd numbers are:
1  3  5  7  9  11  13  15  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45  47  49

# 28. Write a program to print whether a given number is prime number or not

In [ ]:
n=int(input("Enter a number which needed to be checked whether it is prime or not:"))

cnt=0

for i in range(1,n+1):
  if(n%i==0):
    cnt+=1

  if(cnt>2):
    print("Not a Prime Number")
    break

if(cnt<=2):
  print("Prime Number")

Enter a number which needed to be checked whether it is prime or not:51
Not a Prime Number

# 29. Print all the armstrong numbers in the range of 100 to 1000

In [ ]:
for i in range(100,1001):
  N=i
  sum=0

  while(i>0):
    x=i%10
    sum+=x**3
    i=i//10

  if(N==sum):
    print("Armstrong Number: ",N)

Armstrong Number:  153
Armstrong Number:  370
Armstrong Number:  371
Armstrong Number:  407

# 30. The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years. For eg current population is 10000 so the output should be like this:

* 10th year - 10000
* 9th year - 9000
* 8th year - 8100 and so on

In [ ]:
curr_pop=10000

print("popultion in 10th year:",curr_pop)

for i in range(9):
  curr_pop=curr_pop*0.9
  print("Population in {}th year is:{}".format(9-i,round(curr_pop)))

popultion in 10th year: 10000
Population in 9th year is:9000
Population in 8th year is:8100
Population in 7th year is:7290
Population in 6th year is:6561
Population in 5th year is:5905
Population in 4th year is:5314
Population in 3th year is:4783
Population in 2th year is:4305
Population in 1th year is:3874

# 31. Write a program to print all the unique combinations of 1,2,3 and 4

In [ ]:
print("Unique combination of two number:")
for i in range(1,5):
  for j in range(1,5):
    if(i!=j):
      print(i,j)

Unique combination of two number:
1 2
1 3
1 4
2 1
2 3
2 4
3 1
3 2
3 4
4 1
4 2
4 3

# 32. User will provide 2 numbers you have to find the HCF of those 2 numbers

In [ ]:
def hcf(n1,n2):
  div=min(n1,n2)
  hcf=100000

  if(n1%div==0 and n2%div==0):
    hcf=div

  else:
    D=max(n1,n2)
    temp=D%div
    while(temp!=0):
      D=div
      div=temp
      temp=D%div
    hcf=div

  return hcf

In [ ]:
hcf(100,200)

100

In [ ]:
hcf(11,23)

1

In [ ]:
hcf(10,25)

5

# 33. lCM of two numbers

In [ ]:
def lcm(n1,n2):
  for i in range(max(n1,n2),n1*n2+1):
    if(i%n1==0 and i%n2==0):
      return i

In [ ]:
lcm(10,15)

30

In [ ]:
lcm(25,30)

150

# 34. Print first 25 prime numbers

In [ ]:
def is_prime(n):
  cnt=0
  for i in range(1,n//2+1):
    if(n%i==0):
      cnt+=1

  if(cnt>1):
    return False

  else:
    return True


count=0
n=2
while(count<25):
  if(is_prime(n)):
    print(n,end='  ')
    count+=1
  n+=1

2  3  5  7  11  13  17  19  23  29  31  37  41  43  47  53  59  61  67  71  73  79  83  89  97

# 35. Print the first 20 numbers of a Fibonacci series

In [ ]:
f=[]
f.append(1) #since fo and f1 is 1
f.append(1)

for i in range(2,20):
  x=f[i-1]+f[i-2]
  f.append(x)


# print(f)
# len(f)

print("First 20 numbers of a Fibonacci Series are:")
for i in range(len(f)):
  print(f[i],end='  ')

First 20 numbers of a Fibonacci Series are:
1  1  2  3  5  8  13  21  34  55  89  144  233  377  610  987  1597  2584  4181  6765

# 36. Write a program to find the compound interest

In [ ]:
p=float(input("Enter the Principal amount in rupees:"))
r=float(input("Enter the rate of interest in percentage:"))
t=float(input("Enter the time period in year:"))

amount=p*((1+r/100)**t)
ci=amount-p
print("Compound Interest:",ci)

Enter the Principal amount in rupees:1000
Enter the rate of interest in percentage:5
Enter the time period in year:2
Compound Interest: 102.5

# 37. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [ ]:
n=int(input("Enter a number:"))
sum=n
x=n
for i in range(2):
  n=n*10+x
  sum+=n

print("n+nn+nnn is:",sum)

Enter a number:1
n+nn+nnn is: 123

# 38. Take a number from the user and find the number of digits in it.

In [ ]:
n=int(input("Enter a number:"))

cnt=0

while(n>0):
  n=n//10
  cnt+=1

cnt

Enter a number:9852793029

10

# 39. Print all factors of a given number provided by the user.

In [ ]:
n=int(input("Enter a number:"))

print("All factors of the number {} are:".format(n))
for i in range(1,n+1):
  if(n%i==0):
    print(i,end='  ')

Enter a number:16
All factors of the number 16 are:
1  2  4  8  16

# 40. Find the reverse of a number provided by the user(any number of digit)

In [ ]:
n=int(input("Enter a number:"))
rev_n=0

print("Original given number is:",n)
while(n>0):
  tem=n%10
  rev_n=rev_n*10+tem
  n=n//10

print("Reversed number:",rev_n)

Enter a number:123456
Original given number is: 123456
Reversed number: 654321

# 41. Write a program to print the star pattern

In [ ]:
rows=int(input("enter the number of rows:"))

for i in range(1,rows+1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

enter the number of rows:7
*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *

# 42.  program to print star in following way:
1 --> 2 --> 3 --> 2 --> 1

In [ ]:
for i in range(1,4):
  for j in range(1,i+1):
    print('*',end=" ")
  print()

for i in range(2,0,-1):
  for j in range(1,i+1):
    print('*',end=" ")
  print()

*
* *
* * *
* *
*

# 43.  print star pattern of :
*  1 star --> 3 star --> 5 star-->....

In [ ]:
n=int(input("Enter the number of rows:"))

for i in range(1,n+1):
  for j in range(0,2*i-1):
    print("*",end=" ")
  print()

Enter the number of rows:5
*
* * *
* * * * *
* * * * * * *
* * * * * * * * *

# 44. Write a program to print the following pattern
* 1
* 1 2 1
* 1 2 3 2 1
* 1 2 3 4 3 2 1
* 1 2 3 4 5 4 3 2 1

In [ ]:
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end='')
  k=j-1
  while(k>0):
    print(k,end='')
    k=k-1
  print()

1
121
12321
1234321
123454321

# 45. Write a program to print the following pattern
* 1
* 2 3
* 4 5 6
* 7 8 9 10

In [ ]:
num=1
for i in range(1,5):
  for j in range(1,i+1):
    print(num,end=' ')
    num+=1
  print()

1
2 3
4 5 6
7 8 9 10

# 46. Write a program to calculate the sum of the following series till the nth term
# 1/1! + 2/2! + 3/3! + 4/4! +…….+ n/n!
n will be provided by the user

In [ ]:
n=int(input("Enter the value of n:"))

sum=0
fact=1

for i in range(1,n+1):
  fact*=i
  sum+=i/fact

print("Sum of the series is:",sum)

Enter the value of n:3
Sum of the series is: 2.5

# 47. Write a Python Program to Find the Sum of the Series till the nth term:1 + x^2/2 + x^3/3 + … x^n/n
n will be provided by the user

In [ ]:
n=int(input("Enter the value of n:"))
x=int(input("Enter the value of x:"))
sum=1
for i in range(2,n+1):
  sum+=x**i/i

print("Sum of the series is:",sum)

Enter the value of n:4
Enter the value of x:3
Sum of the series is: 34.75

![image.png]()

In [ ]:
x=int(input("Enter the value of x:"))
sum=(x-1)/x
n=7
for i in range(2,n+1):
  sum+=1/2*((x-1)/x)**i
print(sum)

Enter the value of x:4
1.674774169921875

# 49.  Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

In [ ]:
sum=0
cnt=0
while(True):
  n=int(input("enter a number:"))
  if (n!=0):
    sum+=n
    cnt+=1

  else:
    break

print("sum is:",sum)
print("Avg is:",sum/cnt)

enter a number:55
enter a number:56
enter a number:0
sumis: 111
Avg is: 55.5

# 50. Write a program that accepts 2 numbers from the user a numerator and a denominator and then simplifies it
Eg if the num = 5, den = 15 the answer should be ⅓
Eg if the num = 6, den = 9 the answer should be ⅔

In [ ]:
numerator=int(input("Enter the numerator:"))
denominator=int(input("Enter the denominator:"))

gcd=1
for i in range(1,min(numerator,denominator)+1):
  if (numerator%i==0 and denominator%i==0):
    gcd=i
print(numerator//gcd,"/",denominator//gcd)

Enter the numerator:5
Enter the denominator:15
1 / 3

# 51. Find the length of a given string without using the len() function.

In [ ]:
s=input("Enter a string:")
cnt=0

for i in s:
  cnt+=1

print("Length of the string is",cnt)

Enter a string:Hello_world
Length of the string is 11

# 52. Extract username from a given email.
Eg if the email is nitish24singh@gmail.com then the username should be nitish24singh

In [ ]:
email=input("Enter your mail id:")

print("Username :",email[0:email.index('@')])

Enter your mail id:Shek@#dfh
Username : Shek

In [ ]:
email.find("@")

4

In [ ]:
email.index("@")

4

# 53. Count the frequency of a particular character in a provided string. Eg 'hello how are you' is the string, the frequency of h in this string is 2.

In [ ]:
s=input("Enter your string:")
c=input("Enter a character:")
cnt=0

for i in s:
  if (i==c):
    cnt+=1

print("Frequency of",c,"is",cnt)

Enter your string:hello how are you
Enter a character:
Frequency of   is 3

In [ ]:
s.count("h")

2

# 54. Find the index position of a particular character in another string.

In [ ]:
s=input("Enter your string:")
c=input("Enter a character:")

for i in s:
  if(i==c):
    print(s.index(i))
    break

Enter your string:shekhar
Enter a character:a
5

In [ ]:
s.find('r')

6

# 55. Count the number of vowels in a string provided by the user.

In [ ]:
s=input("enter your string:")
Vowels=['a','e','i','o','u']
cnt=0

for i in s:
  if(i in Vowels):
    print("Vowel found:",i,'at index:',s.index(i))
    cnt+=1

print("Number of vowels are:",cnt)

enter your string:Shekhar kumar
Vowel found: e at index: 2
Vowel found: a at index: 5
Vowel found: u at index: 9
Vowel found: a at index: 5
Number of vowels are: 4

# 56. Write a program which can remove a particular character from a string.

In [ ]:
s=input("Enter your string:")
c=input("Enter a character you ant to delete:")
for i in s:
  if(i!=c):
    print(i,end="")

  else:
    continue

Enter your string:Shekhar _ kumar
Enter a character you ant to delete:
Shekhar_kumar

# 57. Write a program that can check whether a given string is palindrome or not.

In [ ]:
s=input("Enter your string:")

for i in range(len(s)//2):
  if s[i]==s[len(s)-i-1]:
    continue
  else:
    print("Not a palindrome")
    break
else:
  print("Palindrome")

Enter your string:malayalam
Palindrome

# 58. Write a python program to remove all the duplicates from a list

In [ ]:
def remove_duplicate(L):
  new_list=[]
  for i in L:
    if i not in new_list:
      new_list.append(i)
  return new_list

In [ ]:
remove_duplicate([1,3,5,3,1,4,2,3,1,2,3,4,1,2,2,3,4,5,1,2,3,4,5])

[1, 3, 5, 4, 2]

In [ ]:
L=[1,3,3,2,3,8,31,13,4,5,6,63,23,3,1]
for i in L:
  # print(i,":",L.index(i))
  if i in L[L.index(i)+1:]:
    L.remove(i)

print(L)

[2, 8, 31, 13, 4, 5, 6, 63, 23, 3, 1]

# 59. Write a python program to convert a string to title case without using the title()

In [ ]:
s=input("Enter your string:")
L= s.split(" ")

print(L)
for i in s.split(" "):
  print(i[0].upper()+i[1:].lower(),end=" ")

Enter your string:shekhar kumar
['shekhar', 'kumar']
Shekhar Kumar

In [ ]:
for i in L:
  i.capitalize()

print(L)
' '.join(L)

['shekhar', 'kumar']

'shekhar kumar'

# 60. Write a python program to find the max item from a list without using the max function

In [ ]:
def max_item(L):
  max=0
  for i in L:
    if i>max:
      max=i
  return max

In [ ]:
max_item([1,3,5,3,1,4,2,3,1,2,3,4,1,2,2,3,4,5,1,2,3,4,5])

5

# 61. Write a python program to reverse a list

In [ ]:
def reverse_list(L):
  new_list=[]
  n=len(L)
  for i in range(n):
    new_list.append(L[n-1-i])

  return new_list

In [ ]:
reverse_list([1,3,5,7,9,7,10])

[10, 7, 9, 7, 5, 3, 1]

# 62. Write a python program to search a given number from a list

In [ ]:
def searcg(L,n):
  for i in L:
    if(i==n):
      return(L.index(i))

In [ ]:
L=[1,2,3,4,5,6,7,8,56]
n=56
print("{} is at {}th place".format(n,searcg(L,n)+1))

56 is at 9th place

# 63. Write a program that can create a new list from a given list where each item in the new list is square of the item of the old list

In [ ]:
def create_list(L):
  new_list=[]
  for i in L:
    new_list.append(i**2)
  return new_list

In [ ]:
create_list([1,2,3,4,5,6,7])

[1, 4, 9, 16, 25, 36, 49]

In [ ]:
L=[1,2,3,4,5,6]
L1=[i**2 for i in L]
print(L1)

[1, 4, 9, 16, 25, 36]

# 64. Write a program that can reverse words of a given string.
Eg if the input is **Hello how are you**
Output should be **you are how Hello**

In [ ]:
S=input("Enter a string:")

L=S.split(" ")
L=L[::-1]
print(" ".join(L))

Enter a string:Hello how are you
you are how Hello

# 65. Write a program that can count the number of words in a given string

In [ ]:
s=input("Enter a string:")

L=s.split(" ")
cnt=0
for i in L:
   cnt+=1
print("Number of words are:",cnt)

Enter a string:hello how are you sam
Number of words are: 5

# 66. Write a program to check if a list is in ascending order or not

In [ ]:
def check_list(L):
  for i in range(1,len(L)):
    if L[i]<=L[i-1]:
      return False
  return True

In [ ]:
check_list([1,2,3,4,5,6,7])

True

In [ ]:
check_list([1,2,3,4,5,6,7,1])

False

# 67. Create 2 lists from a given list where 1st list will contain all the odd numbers from the original list and the 2nd one will contain all the even numbers

In [ ]:
L=[]
n=int(input(" enter the number of elements of the list:"))

for i in range(n):
  x=int(input("enter the {}th element of list:".format(i+1)))
  L.append(x)

print("The original list is:",L)
odd_list=[i for i in L if i%2!=0 ]
even_list=[i for i in L if i%2==0]

print('Odd list is:',odd_list)
print("Even list is:",even_list)

 enter the number of elements of the list:7
enter the 1th element of list:1
enter the 2th element of list:3
enter the 3th element of list:5
enter the 4th element of list:6
enter the 5th element of list:8
enter the 6th element of list:10
enter the 7th element of list:4
The original list is: [1, 3, 5, 6, 8, 10, 4]
Odd list is: [1, 3, 5]
Even list is: [6, 8, 10, 4]

# 68. Write a program to merge 2 list without using the + operator

In [ ]:
def merge_list(L1,L2):
  L3=[]
  for i in L1:
    L3.append(i)

  for i in L2:
    L3.append(i)

  return L3

In [ ]:
merge_list([1,2,3,4],[5,6,7,8,9])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# 69. Write a program to replace an item with a different item if found in the list

In [ ]:
L=[]
n=int(input(" enter the number of elements of the list:"))

for i in range(n):
  x=int(input("enter the {}th element of list:".format(i+1)))
  L.append(x)
print("The original list is:",L)

item=int(input("enter the item which you want to delete from the list:"))
new_item= int(input("Enter the item you want to insert in place of that item:"))

if item in L:
  L[L.index(item)]=new_item
  print(L)
else:
  print("Item not found in the list")

 enter the number of elements of the list:3
enter the 1th element of list:1
enter the 2th element of list:2
enter the 3th element of list:2
The original list is: [1, 2, 2]
enter the item which you want to delete from the list:2
Enter the item you want to insert in place of that item:3
[1, 3, 2]

# 70. Write a program that can convert a 2D list to 1D listWrite a program that can print

In [ ]:
L=[1,2,3,4,[5,6,7]]
res=[]
for i in L:
  if type(i)==list:
    res.extend(i)

  else:
    res.append(i)

print(res)

[1, 2, 3, 4, 5, 6, 7]

# 71. Write a program that can perform union and intersection on 2 given list.

In [ ]:
L1=[1,2,3,4,5,6,7,8,9]
L2=[5,6,7,8,9,10,11,12]

union=[]
intersection=[]

for i in L1:
  if i not in union:
    union.append(i)

for j in L2:
  if j not in L2:
    union.append(j)

for i in L1:
  if i in L2:
    intersection.append(i)

print("Union:",union)
print("Intersection:",intersection)

Union: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Intersection: [5, 6, 7, 8, 9]

# using set function

In [ ]:
list1 = [1, 2, 3, 2, 3]
list2 = [32, 55, 55, 32]

# Convert lists to sets to remove duplicates
set1 = set(list1)
set2 = set(list2)

# Perform union using set union operation
union_set = set1.union(set2)

# Convert the result back to a list while maintaining the order of first appearance
union_list = list(union_set)

print(union_list)

[32, 1, 2, 3, 55]

# 72. Write a program to get the max item of each row of a matrix.

In [ ]:
matrix=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
max=0
for i in matrix:
  for j in i:
    if j>max:
      max=j
  print("Max value of {}th row is: {}".format(matrix.index(i)+1,max))

Max value of 1th row is: 3
Max value of 2th row is: 6
Max value of 3th row is: 9

# 73. Write a program that can convert an integer to string.

In [ ]:
int_n=123
num_s=(str(int_n))
num_s

'123'

In [ ]:
type(num_s)

str

# 74. Write a program to print the shape of a matrix.

In [ ]:
def get_shape(M):
  row=0
  col=0
  for i in M:
    row+=1
  for i in M:
    for j in i:
      col+=1
    break
  return (row,col)

mat=[
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12]
]

row,col=get_shape(mat)

print("Number of rows are:",row)
print("Number of columns are:",col)

Number of rows are: 3
Number of columns are: 4

# 75. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [ ]:
def check_multiplication(m1,m2):
  r1,c1=get_shape(m1)
  r2,c2=get_shape(m2)

  if c1==r2:
    print("Matrix multiplication is possible")
    return True
  else:
    print("Matrix multiplication is not possible")
    return False
m1=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

m2=[
    [1,20],
    [4,15],
    [7,8]
]

check_multiplication(m1,m2)

Matrix multiplication is possible

True

# 76. Write a program to perform matrix multiplication on 2 matrices

In [ ]:
def mutliplication(m1,m2):
  if check_multiplication(m1,m2):
    r1,c1=get_shape(m1)
    r2,c2=get_shape(m2)
    res=[[0 for i in range(c2)] for j in range(r1)]

    for i in range(r1):
      for j in range(c2):
        for k in range(r2):
          res[i][j]+=m1[i][k]*m2[k][j]

    print(res)

In [ ]:
mutliplication(m1,m2)

Matrix multiplication is possible
[[30, 74], [66, 203], [102, 332]]

# 77. Write a program that can sort a given unsorted list. Dont use any built in function for sorting.

In [ ]:
L=[1,5,6,72,5,3,96]
for i in range(1,len(L)):
  if L[i]<L[i-1]:
    temp=L[i]
    L[i]=L[i-1]
    L[i-1]=temp
    i=0
print(L)

[1, 5, 6, 5, 3, 72, 96]

# 78. Write a program that can find the most used word in a bollywood song

In [20]:
def find_most_used_word(lyrics):
  list = lyrics.split(" ")

  d= {}
  for i in list:
    if i in d:
      d[i]+=1
    else:
      d[i]=1


  max = 0
  for i in d:
    if d[i]>max:
      max=d[i]
      most_used_word=i

  print(f"The most used word is '{most_used_word}' which appears {max} times.")

def main():

    # Get lyrics input from user
    lyrics = input("Enter the lyrics of the Bollywood song: ")

    # Find and print the most used word
    find_most_used_word(lyrics)


if __name__ == "__main__":
    main()

Enter the lyrics of the Bollywood song:  hi how are yoy fine hi hi hi
The most used word is 'hi' which appears 4 times.

#79. Assume a list with numbers from 1 to 10 and then convert it into a dictionary where the key would be the numbers of the list and the values would be the square of those numbers.

In [2]:
L = [ i for i in range(1,11)]

print("The list is:",L)

d ={}

for i in L:
  d[i]= i**2

print("The dictionary is:",d)

The list is: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The dictionary is: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

# 80. Write a program to merge two given dictionary

In [7]:
d1={1:10,2:20}
d2={3:30,4:40}


# method 1

for i in d2:
  d1[i]=d2[i]

print(d1)


# method 2

d3 = d1 | d2
print(d3)

{1: 10, 2: 20, 3: 30, 4: 40}
{1: 10, 2: 20, 3: 30, 4: 40}

# 81. Write a program to swap the key value pair for max and min values
* Eg if the dict is like this {‘a’:1,’b’:2,’c’:3}
* Output should be {a:3,b:2,c:1}

In [8]:
D={}

N =int(input("Enter the  number of the entries in the dictionary:"))
for i in range(N):
  k=input("Enter the key:")
  v=int(input("Enter the value:"))
  D[k]=v

print("The original dictionary is:",D)

Enter the  number of the entries in the dictionary:5
Enter the key:a
Enter the value:3
Enter the key:b
Enter the value:2
Enter the key:c
Enter the value:3
Enter the key:d
Enter the value:4
Enter the key:e
Enter the value:5
The original dictionary is: {'a': 3, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [11]:
max=-1
min = 1000000

for i in D:
  if D[i]>max:
    max=D[i]
    max_ind = i

  if D[i]<min:
    min=D[i]
    min_ind = i

D[max_ind]=min
D[min_ind]=max
print("The swapped dictionary is:",D)

The swapped dictionary is: {'a': 3, 'b': 5, 'c': 3, 'd': 4, 'e': 2}

# 82. Write a program to find histogram of a given set of numbers. Take bin size from user. Print the result in the form of a dictionary.

# 83. Write a function that accepts a string and returns the number of upper case chars and lower case chars as a dictionary

In [12]:
def count_case(s):
  cnt_upper = 0
  cnt_lower = 0

  for i in s:
    if i.isupper():
      cnt_upper+=1

    elif i.islower():
      cnt_lower+=1

    else:
      pass

  return {'upper':cnt_upper,'lower':cnt_lower}

s = input("Enter a string:")
count_case(s)

Enter a string:SHEKHAR kumar

{'upper': 7, 'lower': 5}

# 84.  Write a function that accepts a list of strings and performs Bag of words and convert it to numerical vectors.

* https://en.wikipedia.org/wiki/Bag-of-words_model

# 85. Write a dummy program that can perform login and registration using a menu driven program

In [23]:
id = input("Enter your id:")
password = input("Enter your password:")

if id =='20MA' and password == '1234':
  print("Login successful")
else:
  print("Login failed")

Enter your id:20MA
Enter your password:1234
Login successful

# 86. Write a program that accepts neighbors(set of 2D co-ordinates) and a point(single 2D co-ordinate) and tells nearest neighbor(in terms of euclidean distance)

In [34]:
import math

def nearest_neighbor(neighbors, point):
    min_dis = float('inf')
    nearest_ngh = None

    for neighbor in neighbors:
        dis = 0
        for j, k in zip(neighbor, point):
            dis += (k - j)**2
        dis = math.sqrt(dis)
        print(f"Distance to {neighbor}: {dis}")

        if dis < min_dis:
            min_dis = dis
            nearest_ngh = neighbor

    print(f"Nearest neighbor: {nearest_ngh}")

neighbors_d = [(1, 10), (1, 11), (1, 12)]
point_d = (1, 19)

nearest_neighbor(neighbors_d, point_d)

Distance to (1, 10): 9.0
Distance to (1, 11): 8.0
Distance to (1, 12): 7.0
Nearest neighbor: (1, 12)

# 87.  Write a function that accepts a number and returns it’s factorial. You can not use any loop

In [1]:
def fac(N):
  res =1
  if N==1 or 0:
    res =1

  else:
    res =N*fac(N-1)
  return res

No=int(input("Enter a number:"))
fac(No)

Enter a number:5

120