# 1. Write a code to find the minimum among three given numbers.

In [ ]:
num=[]
for i in range(3):
  tem=int(input (F"Enter the {i+1}th number:"))
  num.append(tem)

print("The input numbers are",num)

min=num[0]
for i in range(len(num)):
  if num[i]<min:
    min=num[i]

print("The minimum number is",min)

Enter the 1th number:2
Enter the 2th number:3
Enter the 3th number:4
The input numbers are [2, 3, 4]
The minimum number is 2

# 2. Write a code to check whether a given number is a palindrome.

In [ ]:
N=int(input("enter a number which you want to check for palindrome:"))
num=str(N)

for i in range(len(num)//2):
  if num[i]!=num[-i-1]:
    print("The number is not palindrome")
    break
else:
  print("The number is palindrome")

enter a number which you want to check for palindrome:131
The number is palindrome

# 3. Write a code to find the sum of numbers divisible by 4.The code must allow the user to accept a number and add it to the sum if it is divisible by 4. It should continue accepting numbers as long as the user wants to provide an input and should display the final sum.

In [ ]:
sum=0

while True:
  user_input = input("Enter a number or type (exit) to finish :")

  if user_input.lower() == "exit":
    break

  else:
    num=float(user_input)
    if num%4==0:
      print(f'the number {num} will be added to initial sum value {sum}')
      sum+=num
      print("The current sum is :",sum)

    else:
        print(f"The number {num} can't be added to initial sum value {sum}")
        print("Again provide an input")


print("The final sum is :",sum)

Enter a number or type (exit) to finish :32
the number 32.0 will be added to initial sum value 0
The current sum is : 32.0
Enter a number or type (exit) to finish :36
the number 36.0 will be added to initial sum value 32.0
The current sum is : 68.0
Enter a number or type (exit) to finish :30
The number 30.0 can't be added to initial sum value 68.0
Again provide an input
Enter a number or type (exit) to finish :exit
The final sum is : 68.0

# 4.
 **A three digit number is said to be an “Armstrong number” if the sum of the third power of its individual digits is equal to the number itself.Write a program to check whether a number is armstrong or not.**

In [ ]:
Num=int(input("Enter a three digit number:"))
N=Num
sum=0
while(Num>0):
  temp=Num%10
  sum+= temp**3
  Num=Num//10

if sum==N:
  print("The number is armstrong")
else:
  print("The number is not armstrong")

Enter a three digit number:153
The number is armstrong

# 5
*  **JIT University offering degree courses to students has decided to provide scholarship based on the following details:**


Branch of study ------- Score (%) ---------  Scholarship %
* Arts  --------- Score is at least 90------------ 50
* Arts ---------- Score is an odd number --------- 5
* Engineering ---- Score is more than 85 -------- 50
* Engineering --- Score is divisible by 7 ------  5

**The student is eligible only for one scholarship% even if both the score conditions are valid for the given branch of study. In such cases, students are eligible for the highest**

**If there are 500 students who have joined the university, write a code to calculate and display the final fees to be paid by each student.
You may accept the branch of study, score and course fee as inputs for each student and calculate the final fees to be paid by each student based on formulae given below:
Scholarship amount=course fee * (scholarship%)
Final fee= course fee - scholarship amount**

In [ ]:
fee_Arts = int(input("Enter the fee of the course Arts:"))
fee_Eng = int(input("Enter the fee of the course Engineering:"))
final_fee = 0

for i in range(5):
  course = input(f"Enter the branch of study (A for Arts and Eng for Engineering) for {i+1}th student :")
  score=int(input(f"Enter the score of the {i+1}th student :"))

  if course == "A":
    if score>=90:
      final_fee = fee_Arts - fee_Arts*0.5

    elif score % 2 !=0:
      final_fee = fee_Arts - fee_Arts*0.05

    else:
      final_fee = fee_Arts

  elif course =="Eng":

    if score> 85:
      final_fee = fee_Eng - fee_Eng*0.5

    elif score%7==0:
      final_fee = fee_Eng - fee_Eng*0.05

    else:
      final_fee = fee_Eng


  else:
    print("Invalid input in place of corse name")
    final_fee = "Not Found"


  print(f'The final fee which this student has to pay whose course name is {course} and score is {score} is: {final_fee}')
  print()

Enter the fee of the course Arts:5000
Enter the fee of the course Engineering:6000
Enter the branch of study (A for Arts and Eng for Engineering) for 1th student :A
Enter the score of the 1th student :90
The final fee which this student has to pay whose course name is A and score is 90 is: 2500.0

Enter the branch of study (A for Arts and Eng for Engineering) for 2th student :A+
Enter the score of the 2th student :85
Invalid input in place of corse name
The final fee which this student has to pay whose course name is A+ and score is 85 is: Not Found

Enter the branch of study (A for Arts and Eng for Engineering) for 3th student :Eng
Enter the score of the 3th student :86
The final fee which this student has to pay whose course name is Eng and score is 86 is: 3000.0

Enter the branch of study (A for Arts and Eng for Engineering) for 4th student :Eng
Enter the score of the 4th student :85
The final fee which this student has to pay whose course name is Eng and score is 85 is: 6000

Enter the branch of study (A for Arts and Eng for Engineering) for 5th student :Eng
Enter the score of the 5th student :77
The final fee which this student has to pay whose course name is Eng and score is 77 is: 5700.0

# 6 The flight ticket rates for a round-trip (Mumbai->Dubai) were as follows:
* Rate per Adult: Rs. 37550.0
* Rate per Child: 1/3rd of the rate per adult
* Service Tax: 7% of the ticket amount (including all passengers)

* As it was a holiday season, the airline also offered a 10% discount on the final ticket cost (after inclusion of the service tax).

* Find and display the total ticket cost for a group which had adults and children.

In [ ]:
N_adult=int(input("Enter the number of adults:"))
N_child=int(input("Enter the number of children:"))


ticket_cost = N_adult*37550 + N_child*37550/3
service_tax = ticket_cost*0.07
total_amount = ticket_cost + service_tax
discount_amount = total_amount*0.1
final_amount = total_amount - discount_amount

print(f"The total ticket cost for a group which had {N_adult} adults and {N_child} children is {final_amount}")

Enter the number of adults:3
Enter the number of children:2
The total ticket cost for a group which had 3 adults and 2 children is 132589.05000000002

#7.  Write a python program that displays a message as follows for a given number:
* If it is a multiple of three, display "Zip"
* If it is a multiple of five, display "Zap".
* If it is a multiple of both three and five, display "Zoom".
* If it does not satisfy any of the above given conditions, display "Invalid".

In [5]:
for i in range(5):
  N=int(input("Enter a number:"))

  if N%3 ==0:
    if N%5 == 0:
      print("Zoom")

    else:
      print("Zip")

  elif(N%5 == 0):
    print("Zap")

  else:
    print("Invalid")

Enter a number:25
Zap
Enter a number:15
Zoom
Enter a number:9
Zip
Enter a number:547
Invalid
Enter a number:27
Zip

# 8. 	A teacher in a school wants to find and display the grade of a student based on his/her percentage score. The criterion for grades is as given below:

* Score (both inclusive)     --------------------       Grade
* Between 80 and 100         --------------------         A
* Between 73 and 79         --------------------          B
* Between 65 and 72         --------------------          C
* Between 0 and 64         --------------------           D
* Any other value         --------------------            Z

**Assume that the percentage score is a whole number. Write a python program for the above requirement.**

In [6]:
N = int(input("Enter the number of the students:"))

for i in range(N):
  score = int(input(f"Enter the percentage score of the {i+1}th student:"))

  if score >= 80 and score <=100:
    print(f'Student who has {score} percentage score has grade A')

  elif score >= 73 and score <= 79:
    print(f'Student who has {score} percentage score has grade B')

  elif score >= 65 and score <= 72:
    print(f'Student who has {score} percentage score has grade C')

  elif score >= 0 and score <= 64:
    print(f'Student who has {score} percentage score has grade D')

  else:
    print(f'Student who has {score} percentage score has grade Z')

Enter the number of the students:5
Enter the percentage score of the 1th student:85
Student who has 85 percentage score has grade A
Enter the percentage score of the 2th student:75
Student who has 75 percentage score has grade B
Enter the percentage score of the 3th student:70
Student who has 70 percentage score has grade C
Enter the percentage score of the 4th student:55
Student who has 55 percentage score has grade D
Enter the percentage score of the 5th student:101
Student who has 101 percentage score has grade Z

# 9 Write a python program to find and display the product of three positive integer values based on the rule mentioned below:

* It should display the product of the three values except when one of the integer value is 7. In that case, 7 should not be included in the product and the values to its left also should not be included.
If there is only one value to be considered, display that value itself. If no values can be included in the product, display -1.

* Note: Assume that if 7 is one of the positive integer values, then it will occur only once. Refer the sample I/O given below.
* Sample Input                        --------- Expected Output
* 1, 5, 3                                   --     15
* 3, 7, 8                                   --      8
* 7, 4, 3                                   --     12
* 1, 5, 7                                   --    -1

In [13]:
for i in range(4):

  list=[]
  for i in range(3):
    N=int(input(f"Enter the {i+1}th number:"))
    list.append(N)


  if 7 not in list:
    product =  list[0]*list[1]*list[2]

  else:
    ind = list.index(7)
    print(ind)
    print()

    if ind == 2:
      product =  -1

    elif ind == 0 :
      product = list[1]*list[2]

    elif ind == 1:
      product = list[2]

  print(product)

Enter the 1th number:1
Enter the 2th number:5
Enter the 3th number:3
15
Enter the 1th number:3
Enter the 2th number:7
Enter the 3th number:8
1

8
Enter the 1th number:1
Enter the 2th number:2
Enter the 3th number:7
2

-1
Enter the 1th number:7
Enter the 2th number:2
Enter the 3th number:5
0

10

# 10
**You have x no. of 5 rupee coins and y no. of 1 rupee coins. You want to purchase an item for amount z. The shopkeeper wants you to provide exact change. You want to pay using minimum number of coins. How many 5 rupee coins and 1 rupee coins will you use? If exact change is not possible then display -1.**

In [25]:
Num_1_coin = int (input("Enter the number of 1 rupee coins:"))
Num_5_coin = int(input("Enter the number of 5 rupee coins:"))

amount = int (input("Enter the amount:"))

Num_1 = 0
while True:
  Num_5 = (amount - Num_1)/5
  Num_5 = int(Num_5)

  if  Num_5 <= Num_5_coin and Num_1 <= Num_1_coin and 5*Num_5 + Num_1 == amount:
    print(f"Required number of coins of \n1 rupee is {Num_1} and of \n5 rupee is {Num_5}")
    break

  elif Num_1 > Num_1_coin:
    print("-1")
    break

  else:
    Num_1 +=1

Enter the number of 1 rupee coins:3
Enter the number of 5 rupee coins:5
Enter the amount:18
Required number of coins of
1 rupee is 3 and of
5 rupee is 3

# 11 Write a Python program to generate the next 15 leap years starting from a given year. Populate the leap years into a list and display the list.

In [30]:
def leap_year(yr):
  if ((yr  % 400 == 0) or (yr% 4 == 0 and yr % 100 != 0)):
    return True

  else:
    return False

year = int(input("Enter a year:"))
cnt = 0
leap_year_list = []

while cnt < 15:
  if leap_year(year):
    print(f'{year} is a leap year\n')
    leap_year_list.append(year)
    cnt+=1
  year+=1


print(leap_year_list)

Enter a year:1899
1904 is a leap year

1908 is a leap year

1912 is a leap year

1916 is a leap year

1920 is a leap year

1924 is a leap year

1928 is a leap year

1932 is a leap year

1936 is a leap year

1940 is a leap year

1944 is a leap year

1948 is a leap year

1952 is a leap year

1956 is a leap year

1960 is a leap year

[1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960]

# 12. ARS Gems Store sells different varieties of gems to its customers.

* Write a Python program to calculate the bill amount to be paid by a customer based on the list of gems and quantity purchased.
* Any purchase with a total bill amount above Rs.30000 is entitled to 5% discount.
* If any gem required by the customer is not available in the store, then consider total bill amount to be -1.

* Assume that quantity required by the customer for any gem will always be greater than 0.

* Perform case-sensitive comparison wherever applicable.

* gems_list=["Emerald","Ivory","Jasper","Ruby","Garnet"]

**Price of gems available in the store. gems_list and price_list have one-to-one correspondence**
* price_list=[1760,2119,1599,3920,3999]

**List of gems required by the customer**
* reqd_gems=["Ivory","Emerald","Garnet"]

**Quantity of gems required by the customer. reqd_gems and reqd_quantity have one-to-one correspondence**
* reqd_quantity=[3,10,12]

In [5]:
gems_list=["Emerald","Ivory","Jasper","Ruby","Garnet"]
price_list=[1760,2119,1599,3920,3999]
reqd_gems=["Ivory","Emerald","Garnet"]
reqd_quantity=[3,10,12]
amount = 0

for i in gems_list:
  if i in reqd_gems:
    ind = reqd_gems.index(i)
    ind_for_price = gems_list.index(i)
    amount += reqd_quantity[ind]*price_list[ind_for_price]

if amount > 30000:
  amount = amount*0.95

if amount == 0:
  amount = -1

print(f"The amount to be paid by the customer is {amount}")

The amount to be paid by the customer is 68347.75

#13. Write a python function to check whether three given numbers can form the sides of a triangle.
Hint : Three numbers can be the sides of a triangle if none of the numbers are greater than or equal to the sum of the other two numbers.

In [7]:
a=float(input("Enter the length of first side of triangele:"))
b=float(input("Enter the length of second side of triangele:"))
c=float(input("Enter the length of third side of triangele:"))

if a+b>=c or b+c>=a or c+a>=b:
  print("The three given numbers can't form the sides of a triangle")
else:
  print("The three given numbers can form the sides of a triangle")

Enter the length of first side of triangele:3.2
Enter the length of second side of triangele:6.5
Enter the length of third side of triangele:15
The three given numbers can't form the sides of a triangle

#14. Write a python program to solve a classic ancient Chinese puzzle.
* We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?

In [16]:
no_samples = int(input("Enter the number of samples:"))

for i in range(no_samples):
  N_heads = int(input(f"Enter the number of heads for {i+1}th sample:"))
  N_legs = int(input(f"Enter the number of legs for {i+1}th sample:"))


  N_rabbit = int(N_legs/2 - N_heads)
  N_chicken = N_heads - N_rabbit

  if 2*N_chicken + 4*N_rabbit == N_legs:
    print(f"The number of chickens is {N_chicken} \nThe number of rabbits is {N_rabbit}\n")

  else:
    print("No solution exists for given numbers of heads and legs\n")

Enter the number of samples:4
Enter the number of heads for 1th sample:150
Enter the number of legs for 1th sample:400
The number of chickens is 100
The number of rabbits is 50

Enter the number of heads for 2th sample:3
Enter the number of legs for 2th sample:11
No solution exists for given numbers of heads and legs

Enter the number of heads for 3th sample:3
Enter the number of legs for 3th sample:12
The number of chickens is 0
The number of rabbits is 3

Enter the number of heads for 4th sample:5
Enter the number of legs for 4th sample:10
The number of chickens is 5
The number of rabbits is 0

# 15.  Write a python program which finds the maximum number from num1 to num2 (num2 inclusive) based on the following rules.

* Always num1 should be less than num2
* Consider each number from num1 to num2 (num2 inclusive). Populate the number into a list, if the below conditions are satisfied
* 1. Sum of the digits of the number is a multiple of 3
* 2. Number has only two digits
* 3. Number is a multiple of 5
* Display the maximum element from the list
* In case of any invalid data or if the list is empty, display -1.

In [18]:
num1 = int(input("Enter the first number:"))
num2 = int(input("Enter the second number:"))
list=[]
for i in range(num1,num2+1):
  sum = 0
  temp = i
  while temp>0:
    sum +=temp%10
    temp//=10
  if sum%3==0 and len(str(i))==2 and i%5==0:
    list.append(i)
print(list)
if len(list)==0:
  print("-1")
else:
  print(max(list))

Enter the first number:0
Enter the second number:150
[15, 30, 45, 60, 75, 90]
90

# 16. Write a python program to generate the ticket numbers for specified number of passengers traveling in a flight as per the details mentioned below:
* The ticket number should be generated as **airline:src:dest:number**
where
* Consider AI as the value for airline
* src and dest should be the first three characters of the source and destination cities.
* number should be auto-generated starting from 101

* The program should return the list of ticket numbers of last five passengers.
Note: If passenger count is less than 5, return the list of all generated ticket numbers.

In [21]:
import random

airline = input("Enter the name of airline:")
source = input('Enter the source city:')
destination =input("Enter the destination city:")
no_of_passengers = int(input("Enter the no of passengers:"))

ticket_list=[]

for i in range(no_of_passengers):
  src = source[:3]
  dest = destination[:3]
  num = random.randint(100,999)
  ticket = airline+":"+src+":"+dest+":"+str(num)
  ticket_list.append(ticket)

if len(ticket_list)<5:
  print(ticket_list)

else:
  print(ticket_list[-5:])

Enter the name of airline:AI
Enter the source city:Delhi
Enter the destination city:Bangalore
Enter the no of passengers:50
['AI:Del:Ban:528', 'AI:Del:Ban:296', 'AI:Del:Ban:990', 'AI:Del:Ban:856', 'AI:Del:Ban:827']

# 17. Represent a small bilingual (English-Swedish) glossary given below as a Python dictionary

* {"merry":"god", "christmas":"jul", "and":"och", "happy":"gott", "new":"nytt", "year":"ar"}

* and use it to translate your Christmas wishes from English into Swedish.

* That is, write a python function translate() that accepts the bilingual dictionary and a list of English words (your Christmas wish) and returns a list of equivalent Swedish words.

In [22]:
dictionary = {"merry":"god", "christmas":"jul", "and":"och", "happy":"gott", "new":"nytt", "year":"ar"}
Eng_list = ["merry","christmas"]


def translate(dictionary,eng_list):
  sw_list = []
  for i in eng_list:
    sw_list.append(dictionary[i])
  return sw_list

print(translate(dictionary,Eng_list))

['god', 'jul', 'och', 'gott', 'nytt', 'ar']

# 18. The road transport corporation (RTC) of a city wants to know whether a particular bus-route is running on profit or loss.

* Assume that the following information are given:
* Price per litre of fuel = 70
* Mileage of the bus in km/litre of fuel = 10
* Price(Rs) per ticket = 80

* The bus runs on multiple routes having different distance in kms and number of passengers.
* Write a function to calculate and return the profit earned (Rs) in each route.
* Return -1 in case of loss.

In [24]:
price_fuel = 70
mileage = 10
price_ticket = 80

distance = int(input("Enter the distance of the bus:"))
no_of_passengers = int(input("Enter the number of passengers:"))

total_ticket_price = no_of_passengers*price_ticket
total_fuel_price = distance/mileage*price_fuel

margin = total_ticket_price - total_fuel_price

if margin >0 :
  print(f"This bus route has a profit of {margin} ruppees !")

else:
  print("-1,No profit")

Enter the distance of the bus:105
Enter the number of passengers:9
-1,No profit

#19. Given a string containing uppercase characters (A-Z), compress the string using Run Length encoding. Repetition of character has to be replaced by storing the length of that run.

* Write a python function which performs the run length encoding for a given String and returns the run length encoded String.

* Provide different String values and test your program.

In [ ]:
string = input("Enter a string : ")
list=[]
encoded_list=[]

for i in string:
  if i not in list:
    list.append(i)


for tem in list:
  cnt = 0
  for j in (string):
    if j == tem:
      cnt+=1
  encoded_list.append(str(cnt)+tem)

encoded_string = ''.join(encoded_list)
print(encoded_string)

Enter a string : AAAABBBCCC
4A3B3C

# 20 Write a function, check_palindrome() to check whether the given string is a palindrome or not. The function should return true if it is a palindrome else it should return false.

* Note: Initialize the string with various values and test your program. Assume that all the letters in the given string are all of the same case.
* Example: MAN, civic, WOW etc.

In [ ]:
def check_string_palindrome(string):
  for i in range(len(string)//2):
    if string[i] != string[-i-1]:
      return False
  return True


for i in range(5):
  string = input(f"Enter {i+1}th string : ")
  print(check_string_palindrome(string))
  print()

Enter 1th string : Civic
False

Enter 2th string : ciVic
True

Enter 3th string : CIvic
False

Enter 4th string : wow
True

Enter 5th string : MaN
False

# 21.
 Care hospital wants to know the medical speciality visited by the maximum number of patients. Assume that the patient id of the patient along with the medical speciality visited by the patient is stored in a list. The details of the medical specialities are stored in a dictionary as follows:

* {
"P":"Pediatrics",
"O":"Orthopedics",
"E":"ENT
}


* Write a function to find the medical speciality visited by the maximum number of patients and return the name of the speciality.


* Note:
* 1. Assume that there is always only one medical speciality which is visited by maximum number of patients.
* 2. Perform case sensitive string comparison wherever necessary.

In [ ]:
def most_visited_speciality(patient_visits, specialty_dict):
    # Create a dictionary to count the number of visits to each specialty
    visit_count = {}

    # Iterate through the list of patient visits
    for patient_id, specialty_code in patient_visits:
        # Increment the count for the specialty code
        if specialty_code in visit_count:
            visit_count[specialty_code] += 1
        else:
            visit_count[specialty_code] = 1

    # Find the specialty code with the maximum count
    max_count = -1
    max_specialty_code = None

    for code, count in visit_count.items():
        if count > max_count:
            max_count = count
            max_specialty_code = code

    # Return the full name of the specialty with the maximum count
    return specialty_dict[max_specialty_code]






# Example usage:
patient_visits = [
    ('P001', 'P'),
    ('P002', 'E'),
    ('P003', 'P'),
    ('P004', 'O'),
    ('P005', 'P'),
    ('P006', 'E')
]

specialty_dict = {
    "P": "Pediatrics",
    "O": "Orthopedics",
    "E": "ENT"
}

print(most_visited_speciality(patient_visits, specialty_dict))

Pediatrics